# -*- coding: utf-8 -*-
"""PhysiciAAI_gen.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xgA5_GNdSmhMm4EQkGH9pzmJ3OGAq558
"""



def parseAAI(path,fname):
  PHYCHdi=dict()
  f=open("{}{}".format(path,fname),"r")
  fkey="";fl=0;fl1=0;subD=dict();ln1=[]#;indxname=""
  for line in f:
      if line.startswith("//"):
          PHYCHdi[fkey]=subD;
          fkey="";fl=0;fl1=0;subD=dict();ln1=[]#;indxname=""
      else:
          if line.startswith("H"):
              fkey=line.split("\n")[0].split(" ")[1]
          if fl==1 and fl1==0:
              fl1=1
              if "NA" in line:
                  line=line.replace("NA","0")
              ln2=[float(x) for x in line.split()]
              for i in range(len(ln1)):
                  key=ln1[i].split("/")[0]
                  subD[key]=ln2[i]
          if fl==1 and fl1==1:
              if "NA" in line:
                  line=line.replace("NA","0")
              ln3=[float(x) for x in line.split()]
              for i in range(len(ln1)):
                  key=ln1[i].split("/")[1]
                  subD[key]=ln3[i]
          if line.startswith("I"):
              fl=1;
              ln1=[x.strip() for x in (line.split("\n")[0].split("    ")[1:])]
  return PHYCHdi

parseAAI(path,fname)